#!/usr/bin/env python3
"""Pre-build script: generate src/git_version/_version.py from git tags.

This script uses git-version-utils itself (from source) to determine
the package version, then writes it to _version.py so the built package
has the correct __version__ at runtime.

Usage:
    python tools/write_version.py
"""

import os
import re
import subprocess
import sys
from pathlib import Path


def get_version_from_git() -> str | None:
    """Try to determine version using git-version-utils itself."""
    src_path = str(Path(__file__).parent.parent / "src")
    if src_path not in sys.path:
        sys.path.insert(0, src_path)

    try:
        from git_version.core import GitVersion  # type: ignore[import-untyped]

        gv = GitVersion()
        if gv.tag:
            return gv.version
    except ImportError:
        pass

    # Fallback: call git describe directly
    try:
        result = subprocess.run(
            ["git", "describe", "--match", "v[0-9]*", "--tags"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            tag = result.stdout.strip()
            count_result = subprocess.run(
                ["git", "rev-list", f"{tag}..", "--count"],
                capture_output=True, text=True, timeout=10,
            )
            count = count_result.stdout.strip() if count_result.returncode == 0 else "0"
            stripped = re.sub(r"^[^\d]+", "", tag)
            return f"{stripped}.{count}"
    except Exception:
        pass

    return None


def main() -> None:
    env_version = os.environ.get("GIT_VERSION_UTILS_VERSION")
    version = env_version or get_version_from_git() or "0.0.0"

    version_path = Path(__file__).parent.parent / "src" / "git_version" / "_version.py"
    version_path.parent.mkdir(parents=True, exist_ok=True)
    version_path.write_text(
        f'# file generated by tools/write_version.py\n'
        f"# don't change, don't track in version control\n"
        f'__version__ = "{version}"\n'
        f'__version_tuple__ = {tuple(int(x) if x.isdigit() else x for x in version.split("."))}\n'
    )
    print(f"Version: {version}")


if __name__ == "__main__":
    main()